meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    Meal_plansDetailView,
    Meal_plansListView,
    Meal_plansCreateView,
    Meal_plansUpdateView,
    Meal_plansDeleteView,
)

urlpatterns = [
    path("", Meal_plansListView.as_view(), name="meal_plans_list"),
    path("create/", Meal_plansCreateView.as_view(), name="meal_plans_create"),
    path("<int:pk>/", Meal_plansDetailView.as_view(), name="meal_plans_detail"),
    path(
        "<int:pk>/edit/", Meal_plansUpdateView.as_view(), name="meal_plans_edit"
    ),
    path(
        "<int:pk>/delete/",
        Meal_plansDeleteView.as_view(),
        name="meal_plans_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "", RedirectView.as_view(url=reverse_lazy("recipes_list")), name="home"
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path
from tags.views import (
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(auto_now_add=False)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plan",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

meal_plans/views.py
from django.shortcuts import redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from meal_plans.models import MealPlan
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from recipes.models import Recipe


class Meal_plansListView(ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 4


    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class Meal_plansCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/create.html"
    fields = ["name", "date", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plans_detail", args=[self.object.id])


class Meal_plansDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"
    context_object_name = "meal_plan"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class Meal_plansUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plans_detail", args=[self.object.id])


class Meal_plansDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/create.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete {{ mealplan.name }}?</p>
      {{ form.as_p }}
      <div class="control">
        <button class="button">Delete</button>
      </div>
    </form>
  </main>
{% endblock content %}







# if not owner = yellow page of sadness

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plans_edit' meal_plan.id %}">Edit</a>
      <a href="{% url 'meal_plans_delete' meal_plan.id %}">Delete</a>
    </div>
    <h2>Recipe for {{ meal_plan.name }} {{ meal_plan.date }}</h2>
    {% for recipe in meal_plan.recipes.all %}
        <div class="recipe-card">
          <p><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a><p>
        </div>
      {% endfor %}
{% endblock content %}

# name of the meal plan
# date that it is to be served
# list of names of recipes associated with it 
# each recipe name = link to the recipe page 

# link to the edit view, delete view 
# if not owner of the meal plan, show yellow page of sadness 

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}


{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}




#if person is not the owner = show yellow page of sadness

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block pagination %}
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
  
      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
  
      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
  </div>
{% endblock pagination %}

{% block content %}

<p><a href="{% url 'meal_plans_create' %}">Create New Meal Plan</a></p>
<main class="recipe-grid">
  {% for meal_plan in mealplan_list %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
        <a href="{% url 'meal_plans_detail' meal_plan.id %}">{{ meal_plan.name }}</a>
      </h2>
      {% for recipe in meal_plan.recipes.all %}
        <p>
          <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
        </p>
      {% endfor %}
    </div>
  {% empty %}
    <div>
      <h1>No Meal Plans, yet</h1>
      <p>
        Would you like to
        <a href="{% url 'meal_plans_create' %}">create</a>
        one?
      </p>
    </div>
  {% endfor %}
</main>

{% endblock content %}


</html>